export const LEVEL4_QR_PAY_CONTRACT_ID =
  "CBRAPKIZQKX7D7KYUW75CUPKCXLMCAJGZM3CTRSBB4ZMWBM34QQVDCDI";

export const LEVEL4_QRUSD_TOKEN_CONTRACT_ID =
  "CD4VD6JIWI5SBUM4XHK4RXCPUMFMW5YIZUZICEBRAC2G7BGN4FJTKXKM";

export const LEVEL4_QR_PAY_DEPLOY_HASH =
  "";

export const LEVEL4_QRUSD_TOKEN_DEPLOY_HASH =
  "";

export const LEVEL4_NETWORK = "testnet";
